### ISSUE TITLE
你好，请问这个插件与settings-repositor 有什么区别？

### ISSUE THREAD

**Issue by lizhuoyuan** [jsonbruce/settings-repository-plus#1]
在Android Studio中查询同步多台电脑设置的插件时搜索 Settings Sync 时，
![image](https://user-images.githubusercontent.com/15923901/47060343-d24e1b80-d1ff-11e8-9179-a51057fc1e50.png)
发现了您的插件，想问问这个plus版本 相比于另一个有什么不同

**Comment by maxsxu** [comment]
你好，感谢使用 **Settings Repository Plus** 插件！ @lizhuoyuan 

相比与 IntelliJ 的 **Settings Repository** 插件，**Plus** 版本目前提供了**自定义分支** (Remote Branch) 的功能，旨在保持个人 IntelliJ IDE 配置的统一。

**Comment by lizhuoyuan** [comment]
填写好分支以及github库地址后，点击merge 没有任何响应

**Comment by maxsxu** [comment]
你好，请确认你的 GitHub 仓库 https://github.com/lizhuoyuan/IDE-Setting-Repository  已创建好，谢谢反馈！@lizhuoyuan

**Comment by lizhuoyuan** [comment]
新建了仓库

![image](https://user-images.githubusercontent.com/15923901/47200713-cbfba300-d3a9-11e8-9121-1ff0eb890ccb.png)

 
![image](https://user-images.githubusercontent.com/15923901/47200726-d322b100-d3a9-11e8-85aa-11b6219430ff.png)

点击merge 或是其他按键都没有反应。。。

右下角有这个报错：
![image](https://user-images.githubusercontent.com/15923901/47201074-306b3200-d3ab-11e8-8952-b8b191df1dd7.png)

```
Companion
java.lang.NoSuchFieldError: Companion
	at org.jetbrains.settingsRepository.IcsCredentialsStore.get(IcsCredentialsStore.kt:14)
	at org.jetbrains.settingsRepository.git.JGitCredentialsProvider.doGet(JGitCredentialsProvider.kt:102)
	at org.jetbrains.settingsRepository.git.JGitCredentialsProvider.get(JGitCredentialsProvider.kt:88)
	at org.eclipse.jgit.transport.HttpAuthMethod.authorize(HttpAuthMethod.java:238)
	at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:481)
	at org.eclipse.jgit.transport.TransportHttp.openFetch(TransportHttp.java:313)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:137)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:123)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1271)
	at org.jetbrains.settingsRepository.git.GitExKt.fetch(GitEx.kt:57)
	at org.jetbrains.settingsRepository.git.Pull.fetch(pull.kt:109)
	at org.jetbrains.settingsRepository.git.Pull.fetch$default(pull.kt:104)
	at org.jetbrains.settingsRepository.git.Pull.pull(pull.kt:90)
	at org.jetbrains.settingsRepository.git.Pull.pull$default(pull.kt:78)
	at org.jetbrains.settingsRepository.git.GitRepositoryManager.pull(GitRepositoryManager.kt:217)
	at org.jetbrains.settingsRepository.SyncManager$sync$1$1.invoke(sync.kt:76)
	at org.jetbrains.settingsRepository.SyncManager$sync$1.invoke(sync.kt:133)
	at org.jetbrains.settingsRepository.SyncManager$sync$1.invoke(sync.kt:34)
	at org.jetbrains.settingsRepository.SyncManager$runSyncTask$1$$special$$inlined$runModalTask$1.run(progress.kt:27)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:750)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$10(ApplicationImpl.java:565)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


java.lang.NoClassDefFoundError: com/intellij/ui/layout/Cell
	at org.jetbrains.settingsRepository.AuthFormKt.showAuthenticationForm(authForm.kt:34)
	at org.jetbrains.settingsRepository.git.JGitCredentialsProvider.doGet(JGitCredentialsProvider.kt:111)
	at org.jetbrains.settingsRepository.git.JGitCredentialsProvider.get(JGitCredentialsProvider.kt:88)
	at org.eclipse.jgit.transport.HttpAuthMethod.authorize(HttpAuthMethod.java:238)
	at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:481)
	at org.eclipse.jgit.transport.TransportHttp.openFetch(TransportHttp.java:313)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:137)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:123)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1271)
	at org.jetbrains.settingsRepository.git.GitExKt.fetch(GitEx.kt:57)
	at org.jetbrains.settingsRepository.git.Pull.fetch(pull.kt:109)
	at org.jetbrains.settingsRepository.git.Pull.fetch$default(pull.kt:104)
	at org.jetbrains.settingsRepository.git.Pull.pull(pull.kt:90)
	at org.jetbrains.settingsRepository.git.Pull.pull$default(pull.kt:78)
	at org.jetbrains.settingsRepository.git.GitRepositoryManager.pull(GitRepositoryManager.kt:217)
	at org.jetbrains.settingsRepository.SyncManager$sync$1$1.invoke(sync.kt:76)
	at org.jetbrains.settingsRepository.SyncManager$sync$1.invoke(sync.kt:133)
	at org.jetbrains.settingsRepository.SyncManager$sync$1.invoke(sync.kt:34)
	at org.jetbrains.settingsRepository.SyncManager$runSyncTask$1$$special$$inlined$runModalTask$1.run(progress.kt:27)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:750)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$10(ApplicationImpl.java:565)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.intellij.ui.layout.Cell PluginClassLoader[org.jetbrains.settingsRepositoryPlus, 0.1.0] com.intellij.ide.plugins.cl.PluginClassLoader@6a37c671
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:63)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 33 more


java.lang.NoClassDefFoundError: com/intellij/ui/layout/Cell
	at org.jetbrains.settingsRepository.AuthFormKt.showAuthenticationForm(authForm.kt:34)
	at org.jetbrains.settingsRepository.git.JGitCredentialsProvider.doGet(JGitCredentialsProvider.kt:111)
	at org.jetbrains.settingsRepository.git.JGitCredentialsProvider.get(JGitCredentialsProvider.kt:88)
	at org.eclipse.jgit.transport.HttpAuthMethod.authorize(HttpAuthMethod.java:238)
	at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:481)
	at org.eclipse.jgit.transport.TransportHttp.openFetch(TransportHttp.java:313)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:137)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:123)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1271)
	at org.jetbrains.settingsRepository.git.GitExKt.fetch(GitEx.kt:57)
	at org.jetbrains.settingsRepository.git.Pull.fetch(pull.kt:109)
	at org.jetbrains.settingsRepository.git.Pull.fetch$default(pull.kt:104)
	at org.jetbrains.settingsRepository.git.Pull.pull(pull.kt:90)
	at org.jetbrains.settingsRepository.git.Pull.pull$default(pull.kt:78)
	at org.jetbrains.settingsRepository.git.GitRepositoryManager.pull(GitRepositoryManager.kt:217)
	at org.jetbrains.settingsRepository.SyncManager$sync$1$1.invoke(sync.kt:76)
	at org.jetbrains.settingsRepository.SyncManager$sync$1.invoke(sync.kt:133)
	at org.jetbrains.settingsRepository.SyncManager$sync$1.invoke(sync.kt:34)
	at org.jetbrains.settingsRepository.SyncManager$runSyncTask$1$$special$$inlined$runModalTask$1.run(progress.kt:27)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:750)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$10(ApplicationImpl.java:565)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.intellij.ui.layout.Cell PluginClassLoader[org.jetbrains.settingsRepositoryPlus, 0.1.0] com.intellij.ide.plugins.cl.PluginClassLoader@6a37c671
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:63)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 33 more



```
